version: '3.8'

services:
  mcp-server:
    build: .
    container_name: simple-mcp-server
    command: ["node", "build/http-server.js"]
    ports:
      - "${HTTP_PORT:-8087}:8087"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-simple-mcp-server}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-info}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8087
    volumes:
      # Mount current directory for file operations
      - ./:/workspace:ro
      # Mount logs directory
      - ./logs:/app/logs
    working_dir: /workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: mcp-nginx
    ports:
      - "${EXTERNAL_PORT:-80}:80"
      - "${EXTERNAL_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mcp-server
    networks:
      - mcp-network
    profiles:
      - production

networks:
  mcp-network:
    driver: bridge

volumes:
  logs:
    driver: local